%setup file
DATAPATH = 'C:\data files';
addpath(genpath(DATAPATH));
MAINPATH = 'O:\projects\thh_ont\auditory-attention-in-complex-work-related-auditory-envrionments';
marcmainpath = 'O:\projects\mar_game\';
raw_data_path = ['O:\projects\mar_game\raw_data\'];
chan_path = 'O:\projects\thh_ont\auditory-attention-in-complex-work-related-auditory-envrionments\configs\';
fig_path = char('\\smb.uni-oldenburg.de\home\lorf0331\Documents\MATLAB\Project\OTtracking\Results\figs');
task = {'narrow', 'wide'};

sbj =    {'P001', 'P002','P003','P005', 'P006','P007','P008','P009',...
    'P010','P012','P013', 'P014','P015','P016','P017', 'P018',...
    'P019','P020','P021','P022'};

%the delay between presentation and recording of the system
TriggerSoundDelay = 0.019;

%set up the colors for each model 
%labels:
audi_lb = {'onset',...
    'envelope',...
    'mTRF envelope',...
    'alarm',...
    'irregular',...
    'odd',...
    'odd_in_alarm',...
    'odd_in_irr',...
    'alarmenv',...
    'alarmons',...
    'random',...
    'irrons',...
    'oddons',...
    'oddirr',...
    'oddalarm',...
    'irralarm',...
    'oddirrons',...
    'oddalarmons',...
    'irralarmons',...
    'oddirralarmons',...
    'mel',...
    'melons',...
    'melenv',...
    'melonsenv',...
    'envelope onset',...
    'onsenv',...
    'onsenvmenv',...
    'onsmenv',...
    'alarmmenv',...
    'irrmenv',...
    'oddmenv',...
    'irralarmmenv',...
    'oddirrmenv',...
    'oddalarmmenv',...
    'oddirralarmmenv',...
    'oddirralarm',...
    'melmenv',...
    'melonsmenv',...
    'alarmmel',...
    'irrmel',...
    'oddmel',...
    'irralarmmel',...
    'oddalarmmel',...
    'oddirrmel',...
    'oddirralarmmel'};
%color codes
audi_cl = ["#3DBDA0",...
    "#7eb0d5",...
    "#b2e061",...
    "#bd7ebe",...
    "#ffb55a",...
    "#ccbe50",...
    "#beb9db",...
    "#f44336",...
    "#e81e63",...
    "#9c27b0",...
    "#808080",...
    "#3f51b5",...
    "#2196f3",...
    "#03a9f4",...
    "#00bcd4",...
    "#009688",...
    "#4caf50",...
    "#8bc34a",...
    "#cddc39",...
    "#4e4d82",...
    "#e5836a",...
    "#997cfb",...
    "#fe8f06",...
    "#ff0087",...
    "#887cfb",...
    "#5EB7BB",...
    "#78CF81",...
    "#658CAD",...
    "#8eb34d",...
    "#6a863a",...
    "#35431d",...
    "#cfb17e",...
    "#c1d55e",...
    "#be9e95",...
    "#be999c",...
    "#d19c8a",...
    "#ccb266",...
    "#9cb579",...
    "#d18194",...
    "#f29c62",...
    "#dd9761",...
    "#998974",...
    "#73a09f",...
    "#7496af",...
    "#7b08d2"]';
%RGB triplet conversion
for i = 1:length(audi_cl)
    audi_rgb(i,:) =  sscanf(audi_cl{i}(2:end),'%2x%2x%2x')/255;
end
%dictionary
audi_colors = containers.Map([audi_lb],[audi_cl]);
audi_colorsrgb = containers.Map((audi_lb),num2cell(audi_rgb,2),'UniformValues',false);